# Generated by Django 5.2.7 on 2025-11-22 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('require_push_approval', models.BooleanField(default=False)),
                ('ignore_patterns', models.JSONField(blank=True, default=list)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_projects_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project (New)',
                'verbose_name_plural': 'Projects (New)',
                'db_table': 'projects_project',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coproducer', 'Co-Producer'), ('client', 'Client')], max_length=20)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members_added_new', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members_new', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Member (New)',
                'verbose_name_plural': 'Project Members (New)',
                'db_table': 'projects_projectmember',
                'ordering': ['-added_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['uid'], name='projects_pr_uid_178014_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', '-updated_at'], name='projects_pr_owner_i_242348_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('owner', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
    ]
