# Generated by Django 5.2.7 on 2025-11-22 07:24

import django.db.models.deletion
import versions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file', models.FileField(upload_to=versions.models.blob_upload_path)),
                ('size', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ref_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'File Blob (CAS)',
                'verbose_name_plural': 'File Blobs (CAS)',
                'db_table': 'versions_fileblob',
                'indexes': [models.Index(fields=['hash'], name='versions_fi_hash_87cd3c_idx'), models.Index(fields=['ref_count'], name='versions_fi_ref_cou_fedae1_idx'), models.Index(fields=['created_at'], name='versions_fi_created_2ead6a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('commit_message', models.TextField(blank=True, null=True)),
                ('version_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('is_snapshot', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=versions.models.version_snapshot_path)),
                ('manifest_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_count', models.IntegerField(default=0)),
                ('files_added', models.IntegerField(default=0)),
                ('files_modified', models.IntegerField(default=0)),
                ('files_deleted', models.IntegerField(default=0)),
                ('size_change', models.BigIntegerField(default=0)),
                ('change_details', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions_created_new', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='versions.version')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions_new', to='projects.project')),
            ],
            options={
                'verbose_name': 'Version (New)',
                'verbose_name_plural': 'Versions (New)',
                'db_table': 'versions_version',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingPush',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('commit_message', models.TextField()),
                ('file_list', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('processing', 'Processing'), ('done', 'Done'), ('failed', 'Failed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pushes_approved_new', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes_created_new', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pushes_new', to='projects.project')),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='versions.version')),
            ],
            options={
                'verbose_name': 'Pending Push (New)',
                'verbose_name_plural': 'Pending Pushes (New)',
                'db_table': 'versions_pendingpush',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DownloadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(db_index=True, editable=False, max_length=16, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, null=True)),
                ('zip_file', models.FileField(blank=True, null=True, upload_to=versions.models.download_zip_path)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_requests', to='versions.version')),
            ],
            options={
                'db_table': 'versions_downloadrequest',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['uid'], name='versions_ve_uid_8b9c78_idx'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['project', '-created_at'], name='versions_ve_project_c8ca6f_idx'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['project', 'hash'], name='versions_ve_project_9ccf70_idx'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['project', 'is_snapshot'], name='versions_ve_project_4eac26_idx'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['project', 'status'], name='versions_ve_project_d1cad6_idx'),
        ),
        migrations.AddIndex(
            model_name='version',
            index=models.Index(fields=['project', 'version_number'], name='versions_ve_project_7ac7ba_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpush',
            index=models.Index(fields=['uid'], name='versions_pe_uid_a251ab_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpush',
            index=models.Index(fields=['project', '-created_at'], name='versions_pe_project_0086cf_idx'),
        ),
        migrations.AddIndex(
            model_name='pendingpush',
            index=models.Index(fields=['status'], name='versions_pe_status_719ba0_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadrequest',
            index=models.Index(fields=['uid'], name='versions_do_uid_91d91c_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadrequest',
            index=models.Index(fields=['version', '-created_at'], name='versions_do_version_fd94ff_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadrequest',
            index=models.Index(fields=['status'], name='versions_do_status_e171cd_idx'),
        ),
        migrations.AddIndex(
            model_name='downloadrequest',
            index=models.Index(fields=['expires_at'], name='versions_do_expires_813f4c_idx'),
        ),
    ]
