# Generated by Django 5.2.7 on 2025-11-22 07:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('project_created', 'Project Created'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('version_pushed', 'Version Pushed'), ('version_deleted', 'Version Deleted'), ('push_approved', 'Push Approved'), ('push_rejected', 'Push Rejected'), ('settings_changed', 'Settings Changed'), ('sample_uploaded', 'Sample Uploaded'), ('sample_deleted', 'Sample Deleted')], max_length=30)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs_new', to='projects.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Activity Log (New)',
                'verbose_name_plural': 'Activity Logs (New)',
                'db_table': 'activity_activitylog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='activity_ac_created_d34040_idx'), models.Index(fields=['project', '-created_at'], name='activity_ac_project_eaf88d_idx'), models.Index(fields=['user', '-created_at'], name='activity_ac_user_id_9aae35_idx')],
            },
        ),
    ]
