# Generated by Django 5.2.7 on 2025-11-23 13:21

import django.db.models.deletion
import samples.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleBasket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=samples.models.sample_upload_path)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_new', to='projects.project')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples_uploaded_new', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sample (New)',
                'verbose_name_plural': 'Samples (New)',
                'db_table': 'samples_samplebasket',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['project', '-uploaded_at'], name='samples_sam_project_8c96e9_idx')],
            },
        ),
    ]
