# Generated by Django 5.2.7 on 2025-11-20 05:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('samples', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='samplebasket',
            index=models.Index(fields=['project', '-uploaded_at'], name='samples_sam_project_8c96e9_idx'),
        ),
    ]
