# Generated by Django 5.2.7 on 2025-11-24 10:40

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('samples', '0002_alter_samplebasket_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='samplebasket',
            name='uid',
            field=models.CharField(db_index=True, default=django.utils.timezone.now, editable=False, max_length=16, unique=True),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='samplebasket',
            index=models.Index(fields=['uid'], name='samples_sam_uid_ffe775_idx'),
        ),
    ]
